version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
    #  - ./backend:/backend
      - ./var/db:/var/db
    command: ['./manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - "8000:8000"
    expose:
      - 8000
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    # volumes:
    #   - ./bot:/bot
